// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjobjfgvcgpudeqgfqft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqb2JqZmd2Y2dwdWRlcWdmcWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2NjA0NDgsImV4cCI6MjA3NTIzNjQ0OH0.CCWZiy1x5CVwccepq3S68hV-YYa8aLyENaLjlZ7LlrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});